
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: thisisthesong_development


test:
  <<: *default
  database: thisisthesong_test


#
production:
  <<: *default
  database: thisisthesong_production
  username: thisisthesong
  password: <%= ENV['THISISTHESONG_DATABASE_PASSWORD'] %>
